#ifndef _VECTOR_VECTOR_TYPE_H_
#define _VECTOR_VECTOR_TYPE_H_
#define VECTOR_TYPE_DEFINE_VALUE(x) ((vector_type_id) x)
#define VECTOR_TYPE_CHAR VECTOR_TYPE_DEFINE_VALUE(0x00)
#define VECTOR_TYPE_UNSIGNED_CHAR VECTOR_TYPE_DEFINE_VALUE(0x01)
#define VECTOR_TYPE_SHORT VECTOR_TYPE_DEFINE_VALUE(0x02)
#define VECTOR_TYPE_UNSIGNED_SHORT VECTOR_TYPE_DEFINE_VALUE(0x04)
#define VECTOR_TYPE_INT VECTOR_TYPE_DEFINE_VALUE(0x05)
#define VECTOR_TYPE_UNSIGNED_INT VECTOR_TYPE_DEFINE_VALUE(0x06)
#define VECTOR_TYPE_LONG VECTOR_TYPE_DEFINE_VALUE(0x07)
#define VECTOR_TYPE_UNSIGNED_LONG VECTOR_TYPE_DEFINE_VALUE(0x08)
#define VECTOR_TYPE_FLOAT VECTOR_TYPE_DEFINE_VALUE(0x09)
#define VECTOR_TYPE_DOUBLE VECTOR_TYPE_DEFINE_VALUE(0x0a)
#define VECTOR_TYPE_LONG_INT VECTOR_TYPE_DEFINE_VALUE(0x0b)
#define VECTOR_TYPE_LONG_LONG VECTOR_TYPE_DEFINE_VALUE(0x0c)
#define VECTOR_TYPE_LONG_DOUBLE VECTOR_TYPE_DEFINE_VALUE(0x0d)
#define VECTOR_TYPE_BOOL VECTOR_TYPE_DEFINE_VALUE(0x0e)
#define VECTOR_TYPE_POINTER VECTOR_TYPE_DEFINE_VALUE(0x0f)
#define VECTOR_TYPE_LAST_ID VECTOR_TYPE_POINTER
#endif /* _VECTOR_VECTOR_TYPE_H_ */
